// ═══════════════ DATA ═══════════════

const TILE_TYPES=[
  {id:'beach', name:'해변',icon:'🏖️',cls:'t-beach',flavor:'해변의 모래사장을 걷는다. 파도 소리가 들려온다.',
   events:['res_wood','res_metal','res_food','old_fire','nothing','debris_find','res_rainwater','stormy_shore','abandoned_cook','river_berries'],
   gather:[{tool:'fishing_rod',res:'food',label:'낚시',flavor:'해변에서 낚싯대로 물고기를 잡는다.'}]},
  {id:'forest',name:'숲',  icon:'🌲',cls:'t-forest',flavor:'울창한 숲이다. 여러 동식물의 소리가 들린다.',
   events:['res_wood','res_wood','res_food','res_herb','cbt_boar','cbt_snake','trap_pit','debris_find','res_dew_collect','thorny_brush','cliff_anchor','abandoned_cook','wild_plant_id','wounded_prey'],
   gather:[
     {tool:'gathering_knife',res:'herb',label:'약초채집',flavor:'채집칼로 약초를 모은다.'},
     {tool:'axe',res:'wood',label:'나무베기',flavor:'도끼로 나무를 벤다.'},
   ]},
  {id:'cave',  name:'동굴',icon:'🪨',cls:'t-cave',flavor:'어두운 동굴 입구가 보인다. 안에서 차가운 공기가 흘러나온다.',
   events:['res_metal','res_metal','res_metal','res_stone','cbt_bat','find_shelter','nothing','res_water_spring','dark_cave_path'],
   gather:[
     {tool:'pickaxe',res:'metal',label:'채굴',flavor:'곡괭이로 동굴 벽을 캔다.'},
     {tool:'pickaxe',res:'stone',label:'채석',flavor:'곡괭이로 동굴 바닥을 채석한다.'},
   ]},
  {id:'ruins', name:'폐허',icon:'🏚️',cls:'t-ruins',flavor:'오래된 구조물의 잔해가 흩어져 있다. 무언가 숨겨져 있을 것 같다.',
   events:['res_metal','find_blueprint','cbt_ghost','res_food','survivor_note','haunted_spot','debris_find','ancient_altar'],
   gather:[{tool:'torch',res:'metal',label:'유물탐색',flavor:'횃불로 폐허를 샅샅이 뒤진다.'}]},
  {id:'shore', name:'해안',icon:'🌊',cls:'t-shore',flavor:'거친 파도가 해안을 두드린다. 표류물이 밀려와 있다.',
   events:['res_food','res_metal','find_wreckage','nothing','isolation_dread','res_stone','res_rainwater','stormy_shore','cliff_anchor','wild_plant_id','river_berries'],
   gather:[
     {tool:'fishing_rod',res:'food',label:'낚시',flavor:'해안에서 낚싯대로 낚시한다.'},
     {tool:'canteen',res:'water',label:'물 채집',flavor:'물통에 깨끗한 물을 담는다.'},
   ]},
  {id:'lookout', name:'전망대', icon:'🗼', cls:'t-lookout',
   flavor:'섬 끝, 바다가 보이는 높은 곳. 신호를 보내기 좋아 보인다.',
   events:['nothing','res_wood','find_blueprint'],
   gather:[]},
  {id:'oblivion_lake', name:'망각의 호수', icon:'🌑', cls:'t-lake',
   flavor:'고요하고 검은 수면. 여기에 버리면 다시는 돌아오지 않는다.',
   events:['see_lookout','oblivion_curse','haunted_spot','isolation_dread'],
   gather:[]},
  {id:'oblivion_swamp', name:'망각의 늪', icon:'🕳️', cls:'t-swamp',
   flavor:'검은 수면 아래 무언가가 기억을 삼킨다. 발을 딛는 순간, 무언가가 사라진다.',
   events:['see_lookout','oblivion_curse','haunted_spot'],
   gather:[]},
  {id:'temple', name:'고대 사원', icon:'🏛️', cls:'t-temple',
   flavor:'이끼로 뒤덮인 석조 구조물. 내부에서 으스스한 기운이 흘러나온다.',
   events:['nothing'], gather:[]},
  {id:'thicket', name:'수풀', icon:'🌿', cls:'t-thicket',
   flavor:'빽빽한 덤불. 무언가 숨어있을 것 같다.',
   events:['cbt_boar','cbt_snake'], gather:[], ambushOnReveal:true},

  // ── 균사의 늪 (섬4) 전용 타일 ──
  {id:'swamp', name:'균사 늪', icon:'🍄', cls:'t-swamp',
   flavor:'균사가 뒤덮인 습한 늪. 달콤하고 낯선 냄새가 난다.',
   events:['myc_gather','myc_purify','myc_hazard','cbt_swamp_frog','nothing'],
   gather:[]},
  {id:'fungal_spot', name:'균류 군락', icon:'🌫️', cls:'t-fungal',
   flavor:'거대한 버섯들이 군락을 이루고 있다. 안에서 뭔가 자라고 있는 것 같다.',
   events:['myc_fungal','cbt_spore_walker','myc_gather'], gather:[], fungalDmgOnEnter:3},
  {id:'spore_shrine', name:'포자 제단', icon:'🌀', cls:'t-shrine',
   flavor:'균사가 뒤엉킨 제단. 무언가 강력한 것이 여기서 자라고 있다.',
   events:['nothing'], gather:[]},
  {id:'mycelium_tree', name:'균사 나무', icon:'🌳', cls:'t-myctree',
   flavor:'거대한 균사 나무. 뿌리가 섬 전체를 감싸는 것 같다.',
   events:['myc_tree'], gather:[]},
  {id:'swamp_watch', name:'늪 전망대', icon:'🗼', cls:'t-lookout',
   flavor:'늪 위에 세워진 낡은 전망대. 여기서 신호를 보낼 수 있을 것 같다.',
   events:['nothing'], gather:[]},
];

const WEATHER=[
  {id:'sunny', name:'맑음',    icon:'☀️', eff:'san_+2'},
  {id:'cloudy',name:'흐림',    icon:'☁️', eff:'thi_+5'},
  {id:'rain',  name:'폭우',    icon:'🌧️',eff:'ap_-1'},
  {id:'heat',  name:'폭염',    icon:'🔥', eff:'thi_-14'},
  {id:'fog',   name:'짙은안개',icon:'🌫️',eff:'fog'},
  {id:'storm', name:'폭풍',    icon:'⛈️', eff:'hp_-10'},
];

// dur: n회 사용 후 덱에서 영구 제거. 인스턴스에 curDur 추가
const CARDS=[
  {id:'wood',  name:'목재', icon:'🪵',tag:'resource',atk:0,def:1,n:4,subTags:['무거움'],
   desc:'뗏목·도구 제작 핵심. 방어 판정에 유리.'},
  {id:'metal', name:'고철', icon:'⚙️', tag:'resource',atk:1,def:0,n:3,subTags:['무거움'],
   desc:'도구 제작·공격 판정. 해안에서 많이 발견.'},
  {id:'food',  name:'식량', icon:'🍗',tag:'resource',atk:0,def:0,n:4,use:'eat',dur:3,subTags:['고기'],
   desc:'허기 +22 (칼 보유 시 +30). 내구도 3회 사용 후 소진.'},
  {id:'water', name:'물',   icon:'💧',tag:'resource',atk:0,def:0,n:3,use:'drink',dur:3,subTags:[],
   desc:'갈증 +28. 내구도 3회 사용 후 소진.'},
  {id:'berry', name:'작은 열매',icon:'🍒',tag:'resource',atk:0,def:0,n:0,use:'eat',dur:1,subTags:['열매'],
   desc:'캠프 주변 열매. 허기 +22. 1회용.'},
  {id:'dew',   name:'맺힌이슬', icon:'💦',tag:'resource',atk:0,def:0,n:0,use:'drink',dur:1,subTags:[],
   desc:'이슬을 모아 마신다. 갈증 +28. 1회용.'},
  {id:'herb',  name:'약초', icon:'🌿',tag:'resource',atk:0,def:0,n:2,use:'heal',dur:2,subTags:['열매'],
   desc:'HP +10. 내구도 2회 사용 후 소진.'},
  // 도구 — 패시브 + 수집장비
  {id:'knife',    name:'칼',    icon:'🔪',tag:'tool',atk:4,def:1,n:0,subTags:['날카로움','뾰족함'],
   passiveDesc:'식량 섭취 허기+8 추가 (22→30)',
   desc:'패시브: 식량 회복 증가. 전투 공격력 4.'},
  {id:'torch',    name:'횃불',  icon:'🕯️',tag:'tool',atk:2,def:1,n:0,gatherTool:true,subTags:['불꽃'],
   passiveDesc:'탐색 tool 판정 성공 시 추가 보상 1장',
   desc:'패시브: 탐색 tool 성공 시 추가보상 1장 드로우. ATK2 DEF1.',
   gatherDesc:'🏚️ 폐허에서 수집 가능 → ⚙️고철 1~2개 획득'},
  {id:'rope',     name:'밧줄',  icon:'🪢',tag:'tool',atk:0,def:3,n:0,subTags:['줄'],
   passiveDesc:'카드사용 시 드로우 +1장 (중첩)',
   desc:'패시브: 카드사용 드로우 +1장 (개수만큼 중첩). DEF3.'},
  {id:'axe',      name:'도끼',  icon:'🪓',tag:'tool',atk:3,def:1,n:0,gatherTool:true,subTags:['날카로움','무거움'],
   desc:'🌲 숲에서 나무베기 수집 가능. 전투 ATK3 DEF1.',
   gatherDesc:'🌲 숲에서 수집 가능 → 🪵목재 1~2개 획득'},
  {id:'gathering_knife',name:'채집칼',icon:'🗡️',tag:'tool',atk:2,def:1,n:0,gatherTool:true,subTags:['날카로움','뾰족함'],
   desc:'🌲 숲에서 약초채집 수집 가능. 전투 ATK2 DEF1.',
   gatherDesc:'🌲 숲에서 수집 가능 → 🌿약초 1~2개 획득'},
  {id:'fishing_rod',name:'낚싯대',icon:'🎣',tag:'tool',atk:0,def:2,n:0,gatherTool:true,subTags:[],
   desc:'🏖️해변·🌊해안에서 낚시 수집 가능. DEF2.',
   gatherDesc:'🏖️ 해변·🌊 해안에서 수집 가능 → 🍗식량 1~2개 획득'},
  {id:'canteen',  name:'물통',  icon:'🫙',tag:'tool',atk:0,def:2,n:0,gatherTool:true,subTags:[],
   desc:'🌊 해안에서 물 채집 수집 가능. DEF2.',
   gatherDesc:'🌊 해안에서 수집 가능 → 💧물 1~2개 획득'},
  {id:'pickaxe',  name:'곡괭이',icon:'⛏️',tag:'tool',atk:3,def:0,n:0,gatherTool:true,subTags:['뾰족함','무거움'],
   desc:'🪨 동굴에서 채굴 수집 가능. 전투 ATK3.',
   gatherDesc:'🪨 동굴에서 수집 가능 → ⚙️고철 1~2개 획득'},
  // 전투
  {id:'spear', name:'창',  icon:'🗡️',tag:'combat',atk:8,def:0,n:1,cbtFx:'pierce',subTags:['날카로움','뾰족함'],
   desc:'관통: 공격배정 시 적 방어 완전무시 +4 추가공격.'},
  {id:'shield',name:'방패',icon:'🛡️',tag:'combat',atk:0,def:8,n:1,cbtFx:'block',subTags:['무거움','방어구'],
   desc:'완전방어: 방어배정 시 +5 추가방어. DEF8.'},
  {id:'trap',  name:'함정',icon:'🪤',tag:'combat',atk:5,def:3,n:1,cbtFx:'stun',subTags:['뾰족함'],
   desc:'기절: 배정 시 적 다음라운드 피해 0. 추가ATK3.'},
  // 전투 획득 재료
  {id:'hide',    name:'가죽',    icon:'🦴',tag:'resource',atk:0,def:1,n:0,subTags:[],
   desc:'전투 획득. 가죽갑옷·독칼 제작 재료.'},
  {id:'venom',   name:'독낭',    icon:'🧪',tag:'resource',atk:0,def:0,n:0,subTags:[],
   desc:'전투 획득. 독칼 제작 재료.'},
  {id:'feather', name:'깃털',    icon:'🪶',tag:'resource',atk:0,def:0,n:0,subTags:[],
   desc:'전투 획득. 깃털망토 제작 재료.'},
  {id:'shard',   name:'고대파편',icon:'🔮',tag:'resource',atk:0,def:0,n:0,subTags:[],
   desc:'전투 획득. 유물나침반 제작 재료.'},
  // 제작 아이템
  {id:'leather_armor',name:'가죽갑옷',icon:'🧥',tag:'combat',atk:0,def:4,n:0,subTags:['무거움','방어구'],
   passiveDesc:'전투 시 받는 피해 -2',cbtFx:'armor',
   desc:'패시브: 전투 피해 경감 -2. DEF4.'},
  {id:'poison_knife',name:'독칼',icon:'☠️',tag:'combat',atk:6,def:0,n:0,subTags:['날카로움','뾰족함'],
   cbtFx:'poison',desc:'독: 공격배정 시 적에게 매 라운드 추가 3피해. ATK6.'},
  {id:'feather_cloak',name:'깃털망토',icon:'🧣',tag:'combat',atk:0,def:2,n:0,subTags:[],
   passiveDesc:'도망 비용 HP-15 → HP-2',cbtFx:'cloak',
   desc:'패시브: 도망 비용 대폭 감소. DEF2.'},
  {id:'compass',name:'유물나침반',icon:'🧭',tag:'tool',atk:0,def:0,n:0,subTags:[],
   passiveDesc:'탈출도 +20% 즉시. 탐색 판정 2장 중 유리한 것 선택',
   desc:'고대 유물. 탈출도 즉시 +20%. 탐색 판정 어드밴티지.'},
  {id:'ambush_fist',name:'맨손 기습',icon:'👊',tag:'combat',atk:3,def:0,n:0,cbtFx:'raw',subTags:[],
   desc:'공격카드 없이 맨손 기습. ATK 3(방어무시). 전투 후 소멸.'},
  // 행동 카드
  {id:'running',name:'달리기',icon:'🏃',tag:'action',atk:0,def:0,n:0,subTags:[],
   desc:'[전투·카드사용] 즉시 2장 드로우. 덱 부족 시 버림더미 셔플 후 보충.',
   passiveDesc:'[전투·카드사용] 즉시 2장 드로우'},
  // 기록 카드 — 시작 스킬 선택 시 즉시 발동, 이후 덱에서 쓸모없음
  {id:'rec_collector',name:'수집가의 기록',icon:'📦',tag:'record',tier:'bronze',atk:0,def:0,n:0,subTags:[],
   desc:'[즉시 발동] 덱에 잔해×1, 목재×1, 고철×1 추가.'},
  {id:'rec_morning',name:'아침형 인간의 기록',icon:'🌅',tag:'record',tier:'bronze',atk:0,def:0,n:0,subTags:[],
   desc:'[즉시 발동] 게임 시작 AP+3.'},
  {id:'rec_glutton',name:'먹고 죽은 귀신의 기록',icon:'🍖',tag:'record',tier:'bronze',atk:0,def:0,n:0,subTags:[],
   desc:'[즉시 발동] 허기·갈증·정신력 모두 100으로 채워진 상태로 시작.'},
  {id:'rec_thrifty',name:'절약가의 기록',icon:'💰',tag:'record',tier:'bronze',atk:0,def:0,n:0,subTags:[],
   desc:'[즉시 발동] 덱에 나무열매×2, 맺힌이슬×2 추가.'},
  {id:'rec_geographer',name:'지리학자의 기록',icon:'🌍',tag:'record',tier:'bronze',atk:0,def:0,n:0,subTags:[],
   desc:'[즉시 발동] 시작 위치 3×3 범위(최대 9칸) 타일 공개.'},
  // 구조신호 시스템
  {id:'flare_kit', name:'신호탄 키트', icon:'🧨', tag:'tool', atk:0, def:0, n:0, subTags:['뾰족함','불꽃'],
   gatherTool:false,
   desc:'전망대(🗼) 탐색 시 덱 5장 중 이 카드가 나오면 구조신호 🎆 1개 획득.'},
  {id:'signal', name:'구조신호', icon:'🎆', tag:'tool', atk:0, def:0, n:0, subTags:[],
   gatherTool:false,
   desc:'전망대(🗼)에서 3장 드로우 — 3장 모두 이 카드이면 탈출 성공!'},
  // 상태이상
  {id:'injury',      name:'부상',icon:'🩹',tag:'status',atk:-1,def:-1,n:0,subTags:[],desc:'ATK·DEF -1.'},
  {id:'fear',        name:'공포',icon:'😱',tag:'status',atk:-1,def:-1,n:0,subTags:[],desc:'ATK·DEF -1.'},
  {id:'fatigue',     name:'피로',icon:'😴',tag:'status',atk:0, def:-1,n:0,subTags:[],desc:'DEF -1. 취침 AP회복 -2.'},
  {id:'poison_status',name:'중독',icon:'💀',tag:'status',atk:-1,def:0,n:0,subTags:[],desc:'ATK -1. 매 취침 HP -5.'},
  {id:'amnesia',     name:'망각',icon:'🌀',tag:'status',atk:-1,def:0,n:0,subTags:[],
   desc:'환각이 현실을 침식한다. 탐색 판정 시 정신력-3. 종말 단계에서 확률로 다시 출현한다.',
   passiveDesc:'망각: 탐색 판정 시 정신력-3'},
  {id:'debris', name:'잔해', icon:'🧱', tag:'resource', atk:0, def:0, n:0, subTags:['무거움'],
   desc:'파도에 쓸려온 쓸모없는 잔해. 덱을 차지할 뿐이다. 버려야 가볍다.'},
  {id:'good_sleep', name:'꿀잠', icon:'😪', tag:'resource', atk:0, def:0, n:0, dur:1, use:'good_sleep', subTags:[],
   desc:'숙면의 여운. 사용 시 HP+10, 정신력+8 회복. 내구도 1.'},
  // 돌 재료
  {id:'stone', name:'돌', icon:'🪨', tag:'resource', atk:1, def:1, n:0, subTags:['무거움'],
   desc:'동굴·암석지에서 채집. 돌 무기 제작 재료.'},
  // 새 전투 카드
  {id:'stone_hammer', name:'돌 망치', icon:'⚒️', tag:'combat', atk:6, def:2, n:0, subTags:['무거움'],
   desc:'ATK6 DEF2. 육중한 돌 망치.'},
  {id:'war_club', name:'전쟁 몽둥이', icon:'🏏', tag:'combat', atk:7, def:0, n:0, cbtFx:'crush', subTags:['무거움'],
   desc:'crush: 공격 시 적 DEF 절반 무시. ATK7.'},
  {id:'bone_blade', name:'뼈칼', icon:'🦴', tag:'combat', atk:5, def:1, n:0, cbtFx:'bleed', subTags:['날카로움','뾰족함'],
   desc:'bleed: 공격할 때마다 스택+1, 매 라운드 (스택×2) 지속피해. ATK5.'},
  // 새 방어 카드
  {id:'wooden_shield', name:'나무 방패', icon:'🛡️', tag:'combat', atk:0, def:6, n:0, cbtFx:'block', subTags:['무거움','방어구'],
   desc:'완전방어: 방어배정 시 +5 추가방어. DEF6.'},
  {id:'stone_vest', name:'돌 조끼', icon:'🦺', tag:'combat', atk:0, def:4, n:0, cbtFx:'stone_armor', subTags:['무거움','방어구'],
   passiveDesc:'전투 시 받는 피해 -3',
   desc:'패시브: 전투 피해 경감 -3. DEF4.'},
  // 디버프 카드
  {id:'curse_blade', name:'저주의 칼', icon:'🌑', tag:'combat', atk:4, def:0, n:0, cbtFx:'weaken', subTags:['날카로움','뾰족함'],
   desc:'weaken: 공격 시 적 ATK 영구 -4 (중첩 안됨). ATK4.'},
  {id:'shattering_blow', name:'파쇄 해머', icon:'🔨', tag:'combat', atk:3, def:0, n:0, cbtFx:'shatter', subTags:['무거움'],
   desc:'shatter: 공격 시 적 DEF 영구 -6 (중첩 안됨). ATK3.'},
  // 사원 지도
  {id:'temple_map_piece', name:'사원지도 조각', icon:'🗺️', tag:'resource', atk:0, def:0, n:0, subTags:[],
   desc:'고대 사원 지도의 일부. 3장 모아 사원지도를 만들 수 있다.'},
  // 유인 미끼
  {id:'lure', name:'유인 미끼', icon:'🪤', tag:'tool', atk:0, def:0, n:0, dur:1, use:'lure', subTags:[],
   desc:'사용: 현재 위치에서 야생 동물을 유인. 강제 전투 시작. 내구도 1회.'},
  {id:'temple_map', name:'사원지도', icon:'🏛️', tag:'tool', atk:0, def:0, n:0, dur:1, subTags:[],
   desc:'완성된 사원 지도. 사용 시 지도에 사원 위치 표시. 1회용 — 사용 후 소멸.', use:'temple_map'},
  // ── 스킬 카드 (40장, tag:'skill', n:0 — 덱 초기 미포함) ──
  // 이동 (move)
  {id:'sk_mv_b', name:'가벼운 발', icon:'🥾', tag:'skill', tier:'bronze', atk:0, def:0, n:0,
   passiveDesc:'이동 시 10% 확률로 이동 AP 전액 환급',
   desc:'패시브: 이동할 때마다 10% 확률로 소비한 AP를 돌려받는다.'},
  {id:'sk_mv_s1', name:'바람의 걸음', icon:'💨', tag:'skill', tier:'silver', atk:0, def:0, n:0,
   passiveDesc:'이동 시 HP +1 회복',
   desc:'패시브: 이동할 때마다 HP +1 회복.'},
  {id:'sk_mv_s2', name:'지형 감각', icon:'🗺️', tag:'skill', tier:'silver', atk:0, def:0, n:0,
   passiveDesc:'이동 시 정신력 +1 회복',
   desc:'패시브: 이동할 때마다 정신력 +1 회복.'},
  {id:'sk_mv_s3', name:'탐색자의 눈', icon:'🧭', tag:'skill', tier:'silver', atk:0, def:0, n:0,
   passiveDesc:'탐색 완료 타일 이동 시 AP +1 환급',
   desc:'패시브: 이미 탐색한 타일로 이동하면 AP +1 환급.'},
  {id:'sk_mv_g', name:'자유로운 영혼', icon:'🦅', tag:'skill', tier:'gold', atk:0, def:0, n:0,
   passiveDesc:'이동 시 50% 확률로 이동 AP 전액 환급',
   desc:'패시브: 이동할 때마다 50% 확률로 소비한 AP를 돌려받는다.'},
  // 탐색 (explore)
  {id:'sk_ex_b', name:'날카로운 눈', icon:'🔍', tag:'skill', tier:'bronze', atk:0, def:0, n:0,
   passiveDesc:'탐색 실패 시 10% 확률로 성공 처리',
   desc:'패시브: 탐색 판정 실패 시 10% 추가 성공 기회.'},
  {id:'sk_ex_s1', name:'경험의 빛', icon:'🕯️', tag:'skill', tier:'silver', atk:0, def:0, n:0,
   passiveDesc:'탐색 시 2장 드로우 후 유리한 것 선택 (나침반 보유 시 3장)',
   desc:'패시브: 탐색 판정 시 카드 2장을 드로우해 유리한 카드를 선택. 나침반과 중첩 시 3장.'},
  {id:'sk_ex_s2', name:'꼼꼼한 탐색가', icon:'🎯', tag:'skill', tier:'silver', atk:0, def:0, n:0,
   passiveDesc:'탐색 판정 실패 시 AP 1 환급',
   desc:'패시브: 탐색 실패 시 AP 1 돌려받음.'},
  {id:'sk_ex_s3', name:'기억', icon:'📖', tag:'skill', tier:'silver', atk:0, def:0, n:0,
   passiveDesc:'[카드사용 전용] 현재 타일 재탐색 가능',
   desc:'[카드사용 전용] 현재 위치 탐색 완료 상태 초기화 → 재탐색 가능.', use:'sk_ex_reexplore'},
  {id:'sk_ex_g', name:'천재적 직관', icon:'🌟', tag:'skill', tier:'gold', atk:0, def:0, n:0,
   passiveDesc:'탐색 판정 항상 성공',
   desc:'패시브: 모든 탐색 판정이 자동 성공.'},
  // 수집 (gather)
  {id:'sk_ga_b', name:'채집의 감', icon:'🌾', tag:'skill', tier:'bronze', atk:0, def:0, n:0,
   passiveDesc:'수집 성공률 +10%',
   desc:'패시브: 모든 수집 성공률 +10%.'},
  {id:'sk_ga_s1', name:'알뜰한 손', icon:'📦', tag:'skill', tier:'silver', atk:0, def:0, n:0,
   passiveDesc:'수집 성공 시 획득 +1장',
   desc:'패시브: 수집 성공 시 자원을 1장 더 획득.'},
  {id:'sk_ga_s2', name:'끈기', icon:'⏰', tag:'skill', tier:'silver', atk:0, def:0, n:0,
   passiveDesc:'수집 실패 시 AP 1 환급',
   desc:'패시브: 수집 실패 시 AP 1 돌려받음.'},
  {id:'sk_ga_s3', name:'현장 채집', icon:'🎒', tag:'skill', tier:'silver', atk:0, def:0, n:0,
   passiveDesc:'[카드사용 전용] 현재 타일 즉시 수집 1회 (AP1)',
   desc:'[카드사용 전용] AP 1 소비, 현재 위치 자원 무조건 1장 획득 (25% 확률로 2장).', use:'sk_ga_spot'},
  {id:'sk_ga_g', name:'황금 손', icon:'💰', tag:'skill', tier:'gold', atk:0, def:0, n:0,
   passiveDesc:'모든 카드 획득 2배 (상태이상 포함 — 양날의 검)',
   desc:'패시브: 모든 addCard 호출로 얻는 카드가 2배. 상태이상·잔해도 포함되는 양날의 검.'},
  // 캠프건설 (camp)
  {id:'sk_cp_b', name:'재빠른 건설', icon:'🏕️', tag:'skill', tier:'bronze', atk:0, def:0, n:0,
   passiveDesc:'캠프 건설 AP 비용 -1',
   desc:'패시브: 캠프 건설 AP 비용 -1.'},
  {id:'sk_cp_s1', name:'편안한 밤', icon:'🌙', tag:'skill', tier:'silver', atk:0, def:0, n:0,
   passiveDesc:'캠프 위치 취침 HP 추가 +5',
   desc:'패시브: 캠프에서 취침 시 HP 회복량 +5.'},
  {id:'sk_cp_s2', name:'안전한 야영지', icon:'🛡️', tag:'skill', tier:'silver', atk:0, def:0, n:0,
   passiveDesc:'캠프 위치 취침 이벤트 확률 0% (완전 면제)',
   desc:'패시브: 캠프에서 취침 시 이벤트가 절대 발생하지 않는다.'},
  {id:'sk_cp_s3', name:'모닥불의 온기', icon:'🔥', tag:'skill', tier:'silver', atk:0, def:0, n:0,
   passiveDesc:'꿀잠 카드 사용 효과 2배 (HP+20, 정신력+16)',
   desc:'패시브: 꿀잠 카드를 사용할 때 회복량이 2배로 증가한다.'},
  {id:'sk_cp_g', name:'야영의 달인', icon:'🏰', tag:'skill', tier:'gold', atk:0, def:0, n:0,
   passiveDesc:'캠프 지형 보너스 2배 (cave SAN+6, forest 열매×2, shore 이슬×2)',
   desc:'패시브: 취침 시 캠프 지형 보너스가 2배로 증가한다. (폐허 페널티도 2배)'},
  // 제작 (craft)
  {id:'sk_cr_b', name:'숙련공', icon:'⚒️', tag:'skill', tier:'bronze', atk:0, def:0, n:0,
   passiveDesc:'제작 AP -1 (최소 1)',
   desc:'패시브: 모든 제작 AP 비용 -1.'},
  {id:'sk_cr_s1', name:'재료 절약', icon:'🔩', tag:'skill', tier:'silver', atk:0, def:0, n:0,
   passiveDesc:'제작 시 고철 소비 -1 (최소 0)',
   desc:'패시브: 고철이 포함된 레시피 제작 시 고철 소비 1 감소.'},
  {id:'sk_cr_s2', name:'재활용', icon:'🔄', tag:'skill', tier:'silver', atk:0, def:0, n:0,
   passiveDesc:'제작 완료 후 소비된 재료 중 1종류 1장 돌려받음',
   desc:'패시브: 제작 완료 후 소비된 재료 중 무작위 1종류 1장을 덱에 다시 추가.'},
  {id:'sk_cr_s3', name:'이동 제작소', icon:'🗂️', tag:'skill', tier:'silver', atk:0, def:0, n:0,
   passiveDesc:'[카드사용 전용] 캠프 없이 제작 1회 가능',
   desc:'[카드사용 전용] 다음 제작 1회를 캠프 외 어느 위치에서나 가능.', use:'sk_cr_anywhere'},
  {id:'sk_cr_g', name:'거장', icon:'🏭', tag:'skill', tier:'gold', atk:0, def:0, n:0,
   passiveDesc:'모든 제작 AP 비용 0',
   desc:'패시브: 모든 제작이 완전 무료.'},
  // 카드사용 (carduse)
  {id:'sk_cu_s1', name:'손놀림', icon:'🔀', tag:'skill', tier:'silver', atk:0, def:0, n:0,
   passiveDesc:'카드사용 오픈 시 드로우 +3장',
   desc:'패시브: 카드사용 창을 열 때 추가로 3장을 더 드로우한다.'},
  {id:'sk_cu_s2', name:'음식 전문가', icon:'🍴', tag:'skill', tier:'silver', atk:0, def:0, n:0,
   passiveDesc:'식량·물 사용 효과 +8',
   desc:'패시브: 식량·물 카드 사용 시 회복량 +8.'},
  {id:'sk_cu_s3', name:'선견지명', icon:'👁️', tag:'skill', tier:'silver', atk:0, def:0, n:0,
   passiveDesc:'[전투·카드사용] 덱 위 3장 확인 후 1장 선택 드로우',
   desc:'[전투·카드사용] 덱 맨 위 3장을 보고 1장을 손패(전투핸드)에 추가, 나머지 버림.', use:'sk_cu_peek'},
  {id:'sk_cu_g', name:'신속한 손', icon:'⚡', tag:'skill', tier:'gold', atk:0, def:0, n:0,
   passiveDesc:'[카드사용 전용] 손패의 카드 무작위 1장 소멸',
   desc:'[카드사용 전용] 현재 손패에서 무작위 카드 1장을 영구 소멸시킨다. 덱 정화 효과.', use:'sk_cu_discard'},
  // 취침 (sleep)
  {id:'sk_sl_b', name:'가벼운 잠', icon:'😴', tag:'skill', tier:'bronze', atk:0, def:0, n:0,
   passiveDesc:'취침 이벤트 확률 -15%',
   desc:'패시브: 취침 이벤트 발생 확률 -15%.'},
  {id:'sk_sl_s1', name:'깊은 잠', icon:'🌙', tag:'skill', tier:'silver', atk:0, def:0, n:0,
   passiveDesc:'취침 HP 회복 +8',
   desc:'패시브: 취침 시 HP 회복량 +8.'},
  {id:'sk_sl_s2', name:'명상', icon:'🧘', tag:'skill', tier:'silver', atk:0, def:0, n:0,
   passiveDesc:'취침 정신력 회복 +8',
   desc:'패시브: 취침 시 정신력 회복량 +8.'},
  {id:'sk_sl_s3', name:'꿈에서 깨다', icon:'⏰', tag:'skill', tier:'silver', atk:0, def:0, n:0, dur:1,
   passiveDesc:'[카드사용 전용·1회용] AP +10 즉시 회복',
   desc:'[카드사용 전용] AP +10 즉시 회복. 1회용.', use:'sk_sl_wake'},
  {id:'sk_sl_g', name:'완벽한 수면', icon:'✨', tag:'skill', tier:'gold', atk:0, def:0, n:0,
   passiveDesc:'취침 이벤트 완전 면역 + 꿀잠 카드 자동 생성',
   desc:'패시브: 취침 이벤트 없음 + 매 취침마다 꿀잠 카드 1장 자동 추가.'},
  // 전투 (combat)
  {id:'sk_cb_b', name:'단련된 몸', icon:'🦾', tag:'skill', tier:'bronze', atk:0, def:0, n:0,
   passiveDesc:'전투 피해 -1 (항상)',
   desc:'패시브: 전투에서 받는 피해 -1.'},
  {id:'sk_cb_s1', name:'전투 감각', icon:'⚔️', tag:'skill', tier:'silver', atk:0, def:0, n:0,
   passiveDesc:'전투 드로우 +1장 (5→6장)',
   desc:'패시브: 전투 시작 시 카드 1장을 더 드로우.'},
  {id:'sk_cb_s2', name:'사냥의 기쁨', icon:'🩸', tag:'skill', tier:'silver', atk:0, def:0, n:0,
   passiveDesc:'전투 승리 시 HP +8 회복',
   desc:'패시브: 적을 처치하면 HP +8 회복.'},
  {id:'sk_cb_s3', name:'급소 파악', icon:'🎯', tag:'skill', tier:'silver', atk:0, def:0, n:0,
   passiveDesc:'전투 시작 시 적 DEF -2',
   desc:'패시브: 전투 시작 시 적의 방어력을 2 감소.'},
  {id:'sk_cb_g', name:'힘을 담은 일격', icon:'💥', tag:'skill', tier:'gold', atk:0, def:0, n:0,
   passiveDesc:'[전투 전용] 전투 핸드에서 즉발: 적 HP-10 + 스턴 (보스 35%)',
   desc:'[전투 전용] 전투 핸드에서 즉시 발동. 적 HP-10, 스턴 1라운드 (보스는 35% 확률).', use:'sk_cb_strike'},

  // ── 균사의 늪 (섬4) 전용 카드 ──
  {id:'rotten_food', name:'썩은 음식', icon:'🤢', tag:'status', atk:-1, def:0, n:0, dur:3, subTags:[], use:'eat_rotten',
   desc:'균사에 오염된 음식. 허기+10 HP-5 정신력-3. 내구도 3회 사용 후 소멸.'},
  {id:'spore', name:'포자', icon:'💛', tag:'resource', atk:0, def:0, n:0, subTags:[],
   desc:'균사 관련 이벤트 재료.'},
  {id:'mycelium', name:'균사', icon:'🍄', tag:'resource', atk:0, def:1, n:0, subTags:[],
   desc:'치유와 독의 이중성 재료.'},
  {id:'spore_card', name:'포자 흡입', icon:'☁️', tag:'status', atk:-1, def:-1, n:0, subTags:[],
   passiveDesc:'포자 흡입: 판정 드로우 시 정신력-4',
   desc:'포자에 오염됐다. 탐색 판정 드로우 시 정신력-4.'},
  {id:'myc_chunk', name:'균사 덩어리', icon:'🧫', tag:'resource', atk:0, def:0, n:0, dur:1, use:'eat_chunk', subTags:['고기'],
   desc:'균사로 정화된 먹을거리. 허기+10. 썩지 않는다. 1회용.'},
  {id:'myc_map_piece', name:'균사지도 조각', icon:'🍃', tag:'resource', atk:0, def:0, n:0, subTags:[],
   desc:'포자 제단으로 이어지는 균사 흔적의 조각. 3개를 모아 지도를 만든다.'},
  {id:'myc_map', name:'균사지도', icon:'🗺️', tag:'tool', atk:0, def:0, n:0, dur:1, subTags:[],
   desc:'포자 제단 내부 구조 지도. 보유 중이면 포자 제단 페이즈 도전 가능. 사용 시 영구 해금.', use:'myc_map'},
];

const ENEMIES={
  cbt_boar:{name:'멧돼지',icon:'🐗',hp:30,atk:12,def:4,
    mapDrop:true, chargeEvery:2, patternDesc:'매 2라운드 돌진 (ATK×1.5)',
    encDesc:'덤불 속에서 성난 멧돼지가 으르렁거린다. 강한 돌진이 예상된다.',
    observeReward:[{id:'food',n:2},{id:'hide',n:1}],
    observeText:'멧돼지가 자리를 피한 틈에 먹이와 가죽을 챙겼다.',
    reward:{cards:[{id:'food',n:1}]},
    altCards:[[{id:'hide',n:2}],[{id:'wood',n:2}]],
    rewardDesc:'식량×1 + (가죽×2 또는 목재×2)'},
  cbt_snake:{name:'독사',  icon:'🐍',hp:18,atk:10,def:2,
    mapDrop:true,
    encDesc:'바위 틈에서 독사가 혀를 날름거린다. 독이 있어 물리면 위험하다.',
    observeReward:[{id:'herb',n:1},{id:'venom',n:1}],
    observeText:'독사 굴 근처에서 약초와 독낭을 조심스럽게 채취했다.',
    reward:{cards:[{id:'food',n:1}]},
    altCards:[[{id:'herb',n:1},{id:'venom',n:1}],[{id:'metal',n:2}]],
    rewardDesc:'식량×1 + (약초+독낭 또는 고철×2)',
    penalty:{card:'injury',desc:'독사에게 물려 부상 카드 추가'}},
  cbt_bat:{name:'박쥐떼',icon:'🦇',hp:22,atk:8, def:1,
    mapDrop:true, swarmGain:2, patternDesc:'피해를 못 주면 군집 강화 (ATK+2)',
    encDesc:'동굴 천장에 수백 마리의 박쥐가 매달려 있다. 자극하면 떼로 공격한다.',
    observeReward:[{id:'feather',n:2},{id:'food',n:1}],
    observeText:'박쥐들이 잠든 틈에 깃털을 모으고 먹이를 챙겼다.',
    reward:{cards:[{id:'food',n:1}]},
    altCards:[[{id:'feather',n:2}],[{id:'metal',n:1}]],
    rewardDesc:'식량×1 + (깃털×2 또는 고철×1)',
    penalty:{san:-10,desc:'박쥐떼에 시달려 정신력 -10'}},
  cbt_ghost:{name:'환각존재',icon:'👻',hp:24,atk:10,def:3,
    mapDrop:true, phaseFirst:true, patternDesc:'첫 라운드 피해 무효 (위상 이동)',
    encDesc:'공기가 일그러지며 빛나는 형상이 나타났다. 섬의 저주인가, 환각인가.',
    observeReward:[{id:'shard',n:2}],
    observeText:'형상이 사라진 자리에 고대 파편이 남아 있었다.',
    reward:{san:12,cards:[{id:'food',n:1}]},
    altCards:[[{id:'shard',n:2}],[{id:'metal',n:2}]],
    rewardDesc:'정신력+12 + 식량×1 + (파편×2 또는 고철×2)',
    penalty:{san:-20,desc:'환각에 시달려 정신력 -20'}},
  temple_shade:{name:'어둠의 형상',icon:'🌑',hp:28,atk:11,def:5,
    encDesc:'사원 내부의 어둠이 형상을 이뤄 덤벼든다.',
    observeReward:[{id:'shard',n:1},{id:'stone',n:1}],
    observeText:'어둠의 형상이 흩어지며 조각과 돌이 떨어졌다.',
    reward:{san:5,cards:[{id:'shard',n:1}]},
    altCards:[[{id:'stone',n:2}],[{id:'metal',n:2}]]},
  temple_guardian_knight:{name:'사원 수호자',icon:'⚔️',hp:35,atk:14,def:6,
    encDesc:'갑옷을 두른 석상이 움직인다. 강하고 느리다.',
    observeReward:[{id:'hide',n:1},{id:'stone',n:2}],
    observeText:'수호자가 잠시 정지한 틈에 가죽과 돌을 챙겼다.',
    reward:{cards:[{id:'hide',n:1}]},
    altCards:[[{id:'stone',n:2}],[{id:'metal',n:2}]]},
  boss_stone_idol:{name:'석조 수호신',icon:'🗿',hp:160,atk:10,def:12,
    bossType:'escalate', atkPerRound:4, noFlee:true,
    encDesc:'거대한 석상이 천천히 눈을 뜬다. 방어는 두텁고, 시간이 지날수록 강해진다.',
    reward:{san:30}, altCards:[[{id:'shard',n:3}],[{id:'stone',n:4},{id:'hide',n:2}]]},
  boss_oblivion_herald:{name:'망각의 전령',icon:'👁️',hp:130,atk:6,def:8,
    bossType:'charge', chargeAtk:28, normalAtk:6, _charging:true, noFlee:true,
    encDesc:'붉은 눈이 에너지를 모은다. 충전 중에는 약하지만, 방출하면 치명적이다.',
    reward:{san:30}, altCards:[[{id:'shard',n:3}],[{id:'feather',n:3},{id:'venom',n:2}]]},

  // ── 균사의 늪 (섬4) 전용 몬스터 ──
  cbt_spore_walker:{name:'포자 인간',icon:'🧟',hp:24,atk:10,def:2,
    mycMapDrop:true, pattern:'spore_infect',
    patternDesc:'공격 시 포자 카드를 덱에 주입',
    encDesc:'균사에 잠식된 인간의 잔해. 공격할 때마다 포자 카드가 덱에 섞인다.',
    observeReward:[{id:'spore',n:1}],
    observeText:'포자 인간을 피해 포자를 채취했다.',
    reward:{cards:[{id:'mycelium',n:1}]},
    altCards:[[{id:'spore',n:2}],[{id:'herb',n:1}]],
    rewardDesc:'균사×1 + (포자×2 또는 약초×1)'},
  cbt_mycelium_beast:{name:'균사 수호수',icon:'🦬',hp:38,atk:14,def:4,
    mycMapDrop:true, regenPerRound:6,
    patternDesc:'매 라운드 HP+6 재생',
    encDesc:'거대한 균사 덩어리가 형상을 이루었다. 매 라운드 체력을 재생한다.',
    observeReward:[{id:'mycelium',n:2}],
    observeText:'수호수가 잠시 멈춘 틈에 균사를 채취했다.',
    reward:{cards:[{id:'mycelium',n:2}]},
    altCards:[[{id:'spore',n:2}],[{id:'herb',n:1}]],
    rewardDesc:'균사×2 + (포자×2 또는 약초×1)'},
  cbt_swamp_frog:{name:'늪 개구리',icon:'🐸',hp:18,atk:8,def:1,
    mycMapDrop:true,
    encDesc:'거대한 늪 개구리가 독액을 뱉는다.',
    observeReward:[{id:'herb',n:1},{id:'spore',n:1}],
    observeText:'개구리를 피해 약초와 포자를 채취했다.',
    reward:{cards:[{id:'food',n:1}]},
    altCards:[[{id:'herb',n:1},{id:'venom',n:1}],[{id:'spore',n:1}]],
    rewardDesc:'식량×1 + (약초+독낭 또는 포자×1)',
    penalty:{card:'poison_status',desc:'개구리 독에 중독됐다'}},
  boss_great_mycelium:{name:'대균사',icon:'🌀',hp:140,atk:18,def:6,
    bossType:'mycelium_boss', noFlee:true, _phase2:false,
    encDesc:'섬의 균사 네트워크가 형상을 이루었다. HP 50% 이하에서 포자 폭발이 시작된다.',
    reward:{san:30}, altCards:[[{id:'mycelium',n:3}],[{id:'spore',n:3},{id:'herb',n:2}]]},
  boss_rot_queen:{name:'부패의 여왕', icon:'🍄', hp:130, atk:15, def:5,
    bossType:'rot_queen', noFlee:true, _phase2:false,
    encDesc:'부패의 여왕이 모습을 드러냈다. 매 라운드 네 식량을 오염시키고, 오염된 것을 먹어 회복한다.',
    patternDesc:'매 라운드 덱의 식량 1장→썩은음식 변환. 썩은음식이 ATK존에 있으면 적 HP+15',
    reward:{san:25}, altCards:[[{id:'mycelium',n:3}],[{id:'myc_map_piece',n:1},{id:'spore',n:3}]]},
  boss_spore_tyrant:{name:'포자 폭군', icon:'☁️', hp:160, atk:12, def:4,
    bossType:'spore_tyrant', noFlee:true, _phase2:false, regenPerRound:4,
    encDesc:'포자 폭군이 포자를 뿜어낸다. 매 라운드 독이 누적되고, 체력을 재생한다.',
    patternDesc:'매 라운드 독 1스택 부여 + HP+4 재생. HP 40% 이하: 분노(ATK+6)',
    reward:{san:25}, altCards:[[{id:'mycelium',n:3}],[{id:'myc_map_piece',n:1},{id:'herb',n:3}]]},
};

const EVENTS={
  res_wood:{
    name:'목재 더미 발견',flavor:'해안가에 파도에 쓸려온 통나무가 쌓여 있다.',
    choices:[
      {label:'꼼꼼히 수거',icon:'🪵',req:'resource',reward:{card:'wood',n:3},failPen:{hun:-12},
       greatCard:'axe',greatBonus:{card:'wood',n:2,ap:1},desc:'자원판정. 성공:목재×3 / 대성공(도끼):+목재×2+AP환급 / 실패:허기-12'},
      {label:'빠르게만 챙긴다',icon:'👀',req:null,reward:{card:'wood',n:1},desc:'무조건 성공. 목재×1.'},
    ]},
  res_food:{
    name:'먹을 것 발견',flavor:'덤불 사이에 먹을 수 있을 것 같은 것들이 보인다.',
    choices:[
      {label:'독 여부 확인',icon:'🔍',req:'tool',reward:{card:'food',n:2},failPen:{hp:-8},
       greatCard:'gathering_knife',greatBonus:{card:'food',n:1},desc:'도구판정. 성공:식량×2 / 대성공(채집칼):+식량'},
      {label:'그냥 조금 먹어본다',icon:'🍽️',req:'resource',reward:{card:'food',n:1},failPen:{san:-8},desc:'자원판정. 실패:정신력↓'},
      {label:'효율적으로 손질',icon:'🔪',req:null,subReq:'날카로움',reward:{card:'food',n:2},failPen:{},
       desc:'#날카로움 판정. 성공:식량×2 / 실패:빈손'},
    ]},
  res_metal:{
    name:'고철 잔해 발견',flavor:'부서진 기계 부품들이 흩어져 있다.',
    choices:[
      {label:'꼼꼼히 분해',icon:'⚙️',req:'tool',reward:{card:'metal',n:2},failPen:{hp:-6},
       greatCard:'pickaxe',greatBonus:{card:'metal',n:2,ap:1},desc:'도구판정. 성공:고철×2 / 대성공(곡괭이):+고철×2+AP'},
      {label:'보이는 것만 줍기',icon:'👋',req:'resource',reward:{card:'metal',n:1},desc:'자원판정. 실패:빈손.'},
    ]},
  res_herb:{
    name:'약초 군락 발견',flavor:'상처에 좋아 보이는 풀들이 자라고 있다.',
    choices:[
      {label:'약효 있는 것 선별',icon:'🌿',req:'tool',reward:{card:'herb',n:2},failPen:{san:-5},
       greatCard:'gathering_knife',greatBonus:{card:'herb',n:1},desc:'도구판정. 성공:약초×2 / 대성공(채집칼):+약초'},
      {label:'보이는 대로 채집',icon:'🤲',req:'resource',reward:{card:'herb',n:1},desc:'자원판정. 실패:빈손.'},
      {label:'정밀하게 잘라낸다',icon:'✂️',req:null,subReq:'날카로움',reward:{card:'herb',n:2},failPen:{},
       desc:'#날카로움 판정. 성공:약초×2 / 실패:빈손'},
    ]},
  find_shelter:{
    name:'은신처 발견',flavor:'폭풍을 피할 수 있는 작은 동굴 입구가 보인다. 무거운 잔해가 입구를 막고 있다.',
    choices:[
      {label:'잔해를 밀어낸다',icon:'🪨',req:null,subReq:'무거움',reward:{san:10,card:'metal',n:1},failPen:{hp:-15},
       desc:'#무거움 카드만 성공. 성공:정신력+10+고철 / 실패:HP-15'},
      {label:'깊이 탐색한다',icon:'🕯️',req:'tool',reward:{san:10,card:'metal',n:1},failPen:{hp:-15},
       greatCard:'torch',greatBonus:{san:8,ap:2},desc:'도구판정. 성공:정신력+10+고철 / 대성공(횃불):+정신력+8+AP×2 / 실패:HP-15'},
      {label:'입구만 살핀다',icon:'👁️',req:null,reward:{san:5},desc:'무조건. 정신력+5.'},
    ]},
  find_blueprint:{
    name:'탈출 설계도!',flavor:'낡은 상자 안에 뭔가 적힌 종이가 보인다.',
    choices:[
      {label:'신중히 분석',icon:'📐',req:'tool',reward:{escape:30},failPen:{san:-10},
       greatCard:'torch',greatBonus:{escape:15,ap:1},desc:'도구판정. 성공:탈출+30% / 대성공(횃불):+15%+AP'},
      {label:'일단 챙긴다',icon:'🗂️',req:'resource',reward:{escape:15},desc:'자원판정. 실패:탈출 없음.'},
    ]},
  find_wreckage:{
    name:'난파 잔해',flavor:'배의 잔해가 해안에 널려있다.',
    choices:[
      {label:'잠수해서 수거',icon:'🤿',req:'tool',reward:{card:'metal',n:3},failPen:{hp:-12},
       greatCard:'rope',greatBonus:{card:'metal',n:2},desc:'도구판정. 성공:고철×3 / 대성공(밧줄):+고철×2'},
      {label:'육지 잔해만',icon:'🏖️',req:'resource',reward:{card:'metal',n:1},desc:'자원판정. 실패:빈손.'},
      {label:'무게로 뜯어낸다',icon:'⚒️',req:null,subReq:'무거움',reward:{card:'metal',n:2},failPen:{hp:-5},
       desc:'#무거움 판정. 성공:고철×2 / 실패:HP-5'},
    ]},
  nothing:{
    name:'아무것도 없음',flavor:'이 주변을 둘러봤지만 특별한 것은 없었다.',
    choices:[
      {label:'한 번 더 살핀다',icon:'🔎',req:'tool',reward:{card:'food',n:2,ap:1},failPen:{hp:-8},
       greatCard:'torch',greatBonus:{card:'metal',n:2},desc:'도구판정. 성공:식량×2+AP환급 / 대성공(횃불):고철×2 / 실패:HP-8'},
      {label:'그냥 돌아간다',icon:'↩️',req:null,reward:{},desc:'무조건. 빈손.'},
    ]},
  survivor_note:{
    name:'생존자의 흔적',flavor:'누군가 이 곳에 있었던 것 같다. 낡은 메모와 흔적이 남아있다.',
    choices:[
      {label:'흔적을 철저히 조사',icon:'🕯️',req:'tool',
       reward:{card:'metal',n:1,escape:15},failPen:{hp:-8},
       greatCard:'torch',greatBonus:{card:'wood',n:1,ap:2},
       desc:'도구판정. 성공:고철×1+탈출+15% / 대성공(횃불):+목재+AP×2 / 실패:HP-8'},
      {label:'메모만 빠르게 읽는다',icon:'📝',req:null,
       reward:{escape:5},
       desc:'무조건. 탈출도+5%.'},
    ]},
  trap_pit:{
    name:'야생 덫 구덩이',flavor:'덤불 사이에 정교하게 파인 함정이 보인다. 날카로운 가시와 먹이가 걸려든 것 같다.',
    choices:[
      {label:'가시를 잘라낸다',icon:'✂️',req:null,subReq:'날카로움',
       reward:{card:'food',n:3},failPen:{hp:-12},
       desc:'#날카로움 카드만 성공. 성공:식량×3 / 실패:HP-12'},
      {label:'전리품을 회수한다',icon:'🎯',req:'resource',
       reward:{card:'food',n:3},failPen:{hp:-12},
       greatCard:'gathering_knife',greatBonus:{card:'hide',n:1},
       desc:'자원판정. 성공:식량×3 / 대성공(채집칼):+가죽×1 / 실패:HP-12'},
      {label:'건드리지 않고 지나친다',icon:'🚶',req:null,
       reward:{},
       desc:'무조건. 빈손. 안전.'},
    ]},
  haunted_spot:{
    name:'으스스한 기운',flavor:'이 폐허에서 무언가를 강하게 느꼈다. 환각인지 현실인지 경계가 흐려지기 시작한다.',
    choices:[
      {label:'정신을 다잡고 탐색한다',icon:'🕯️',req:'tool',
       reward:{card:'metal',n:1},failPen:{san:-18},
       greatCard:'torch',greatBonus:{san:10,escape:5},
       desc:'도구판정. 성공:고철×1 / 대성공(횃불):정신력+10+탈출+5% / 실패:정신력-18'},
      {label:'방어구 착용 후 탐색',icon:'🛡️',req:null,subReq:'방어구',
       reward:{card:'metal',n:1,san:5},failPen:{san:-8},
       desc:'#방어구 판정. 성공:고철×1+정신력+5 / 실패:정신력-8'},
      {label:'이 곳을 빨리 벗어난다',icon:'🏃',req:null,
       reward:{san:-6},
       desc:'무조건. 황급히 벗어나지만 정신력-6.'},
    ]},
  isolation_dread:{
    name:'극도의 고립감',flavor:'수평선을 바라보다 아무도 없다는 사실이 갑자기 절망적으로 느껴진다.',
    choices:[
      {label:'탈출을 생각하며 버틴다',icon:'🌊',req:'resource',
       reward:{san:8,escape:5},failPen:{san:-15},
       desc:'자원판정. 성공:정신력+8+탈출+5% / 실패:정신력-15'},
      {label:'불을 밝혀 어둠을 몰아낸다',icon:'🔥',req:null,subReq:'불꽃',
       reward:{san:12},failPen:{san:-8},
       desc:'#불꽃 판정. 성공:정신력+12 / 실패:정신력-8'},
      {label:'그냥 눈을 감는다',icon:'😔',req:null,
       reward:{san:-5},
       desc:'무조건. 체념하며 버틴다. 정신력-5.'},
    ]},
  old_fire:{
    name:'꺼진 모닥불 흔적',flavor:'누군가 야영했던 자리다. 숯불 주위에 쓸만한 것이 남아있을지도 모른다.',
    choices:[
      {label:'재와 주변을 뒤진다',icon:'🔥',req:'resource',
       reward:{card:'wood',n:2,san:5},failPen:{hun:-10},
       greatCard:'axe',greatBonus:{card:'wood',n:1,ap:1},
       desc:'자원판정. 성공:목재×2+정신력+5 / 대성공(도끼):+목재+AP환급 / 실패:허기-10'},
      {label:'횃불로 점화한다',icon:'🕯️',req:null,subReq:'불꽃',
       reward:{san:12,ap:1},failPen:{},
       desc:'#불꽃 판정. 성공:정신력+12+AP환급 / 실패:빈손'},
      {label:'불을 다시 피운다',icon:'🕯️',req:null,
       reward:{san:8},
       desc:'무조건. 따뜻한 불로 정신력+8 회복.'},
    ]},
  see_lookout:{
    name:'저 멀리 전망대',
    flavor:'안개 사이로 높은 구조물이 희미하게 보인다. 저 위에서라면 신호를 보낼 수 있을 것 같다.',
    choices:[
      {label:'위치를 기억한다',icon:'🗼',req:null,
       reward:{revealTile:'lookout',san:5},
       desc:'무조건. 전망대 위치가 지도에 표시된다. 정신력+5.'},
      {label:'그냥 지나친다',icon:'🚶',req:null,
       reward:{},
       desc:'무조건. 빈손.'},
    ]},
  debris_find:{
    name:'파편 더미',
    flavor:'해안에 밀려온 잡동사니가 쌓여 있다. 뒤지면 뭔가 나오겠지만, 손이 더러워진다.',
    choices:[
      {label:'목재 위주로 수거',icon:'🪵',req:null,
       reward:{cards:[{id:'debris',n:1,force:true},{id:'wood',n:2}]},
       desc:'무조건. 잔해×1 추가 + 목재×2 획득.'},
      {label:'고철 위주로 수거',icon:'⚙️',req:null,
       reward:{cards:[{id:'debris',n:1,force:true},{id:'metal',n:1}]},
       desc:'무조건. 잔해×1 추가 + 고철×1 획득.'},
      {label:'잔해를 정리한다',icon:'🧹',req:null,
       devourDrawn:true,devourTag:'resource',reward:{},
       desc:'무조건. 덱의 자원 카드 1장을 뒤집어 소멸.'},
    ]},
  res_water_spring:{
    name:'지하 샘 발견',flavor:'동굴 깊은 곳에서 맑은 물이 솟아오른다. 음용하기 좋을 것 같다.',
    choices:[
      {label:'조심스럽게 채수',icon:'💧',req:'tool',reward:{card:'water',n:2},failPen:{hp:-5},
       greatCard:'canteen',greatBonus:{card:'water',n:2,ap:1},
       desc:'도구판정. 성공:물×2 / 대성공(물통):+물×2+AP환급 / 실패:HP-5'},
      {label:'손으로 떠마신다',icon:'🤲',req:null,reward:{card:'water',n:1},
       desc:'무조건 성공. 물×1.'},
    ]},
  res_rainwater:{
    name:'빗물 웅덩이',flavor:'바위 위에 고인 빗물이 보인다. 마실 수 있을 것 같다.',
    choices:[
      {label:'깨끗이 걸러 채집',icon:'💦',req:'tool',reward:{card:'water',n:2},failPen:{san:-6},
       greatCard:'canteen',greatBonus:{card:'water',n:2},
       desc:'도구판정. 성공:물×2 / 대성공(물통):+물×2 / 실패:정신력-6'},
      {label:'그냥 마신다',icon:'🥤',req:'resource',reward:{card:'water',n:1},failPen:{hp:-5},
       desc:'자원판정. 성공:물×1 / 실패:HP-5'},
    ]},
  res_dew_collect:{
    name:'아침 이슬',flavor:'나뭇잎 위에 이슬이 맺혀 있다. 조심스럽게 모으면 마실 물이 된다.',
    choices:[
      {label:'잎을 훑어 모은다',icon:'🌿',req:'resource',reward:{card:'water',n:1},
       desc:'자원판정. 성공:물×1 / 실패:빈손.'},
      {label:'빠르게 훑어간다',icon:'💨',req:null,reward:{card:'dew',n:1},
       desc:'무조건 성공. 맺힌이슬×1.'},
    ]},
  res_stone:{
    name:'암석 노출지대',
    flavor:'풍화된 바위들이 드러나 있다. 손으로 캐면 좋은 돌을 얻을 수 있을 것 같다.',
    choices:[
      {label:'꼼꼼히 채석',icon:'🪨',req:'tool',
       reward:{card:'stone',n:3},failPen:{hp:-8},
       greatCard:'pickaxe',greatBonus:{card:'stone',n:2,ap:1},
       desc:'도구판정. 성공:돌×3 / 대성공(곡괭이):+돌×2+AP환급 / 실패:HP-8'},
      {label:'조금만 줍기',icon:'🤲',req:'resource',
       reward:{card:'stone',n:1},desc:'자원판정. 성공:돌×1 / 실패:빈손.'},
    ]},
  temple_event_1a:{
    name:'사원 입구 — 돌의 기운',
    flavor:'두꺼운 석벽에서 묵직한 힘이 느껴진다. 이 존재는 두꺼운 방어를 뚫어야 쓰러뜨릴 수 있을 것 같다. 시간이 지날수록 더 강해진다. — 관통·분쇄 능력이 필요하다.',
    choices:[
      {label:'목재를 바친다',icon:'🪵',req:null,
       reward:{san:15,ap:1,devourCard:'wood'},desc:'목재 1장 소멸. 정신력+15, AP환급.'},
      {label:'돌 재료를 바친다',icon:'🪨',req:null,
       reward:{hp:25,san:5,devourCard:'stone'},desc:'돌 1장 소멸. HP+25, 정신력+5.'},
      {label:'그냥 지나친다',icon:'🚶',req:null,reward:{},desc:'무조건. 보상 없음.'},
    ]},
  temple_event_1b:{
    name:'사원 입구 — 어둠의 기운',
    flavor:'공기 중에 어두운 에너지가 응집되고 있다. 충전이 완료되면 압도적인 한 방을 날린다. 방어하거나, 기절시키거나. — 방패나 기절 능력이 필요하다.',
    choices:[
      {label:'목재를 바친다',icon:'🪵',req:null,
       reward:{san:15,ap:1,devourCard:'wood'},desc:'목재 1장 소멸. 정신력+15, AP환급.'},
      {label:'고철을 바친다',icon:'⚙️',req:null,
       reward:{hp:20,san:5,devourCard:'metal'},desc:'고철 1장 소멸. HP+20, 정신력+5.'},
      {label:'그냥 지나친다',icon:'🚶',req:null,reward:{},desc:'무조건. 보상 없음.'},
    ]},
  temple_event_2:{
    name:'사원 심부 제단',
    flavor:'더 깊은 곳. 제단이 교환을 요구한다. 낡은 것을 내어주면 더 강한 것으로 돌아온다.',
    choices:[
      {label:'전투카드를 바친다',icon:'⚔️',req:null,
       reward:{devourTagCard:'combat',card:'spear',n:1},
       desc:'무조건. 보유 전투카드 1장 소멸 → 창🗡️ 획득.'},
      {label:'도구를 바친다',icon:'🔧',req:null,
       reward:{devourTagCard:'tool',card:'shield',n:1},
       desc:'무조건. 보유 도구카드 1장 소멸 → 방패🛡️ 획득.'},
      {label:'쉬어간다',icon:'🛌',req:null,
       reward:{hp:20,san:10},
       desc:'무조건. HP+20, 정신력+10 회복.'},
    ]},
  oblivion_curse:{
    name:'망각의 기운',
    flavor:'어두운 수면이 마음속으로 파고드는 것 같다. 기억의 일부가 흐릿해지는 느낌이다.',
    choices:[
      {label:'정신을 붙잡는다',icon:'🧠',req:'tool',
       reward:{san:5},failPen:{san:-10,card:'amnesia'},
       desc:'도구판정. 성공:정신력+5 / 실패:정신력-10+망각 카드 추가.'},
      {label:'몸에 맡긴다',icon:'😶',req:null,
       reward:{san:-5},curseDeck:'amnesia',
       desc:'무조건. 정신력-5. 망각 카드가 덱에 스며든다.'},
    ]},

  // ── 서브태그 강화 신규 이벤트 ──

  dark_cave_path:{
    name:'동굴 어둠의 통로',
    flavor:'더 깊은 곳에 무언가 있을 것 같다. 하지만 완전한 어둠이 앞을 막는다.',
    choices:[
      {label:'횃불로 전진',icon:'🕯️',req:null,subReq:'불꽃',
       reward:{card:'metal',n:2,san:5},failPen:{hp:-8},
       desc:'#불꽃 판정. 성공:고철×2+정신력+5 / 실패:HP-8'},
      {label:'손으로 더듬어 전진',icon:'🤲',req:'resource',
       reward:{card:'metal',n:1},failPen:{hp:-8},
       desc:'자원판정. 성공:고철×1 / 실패:HP-8'},
      {label:'포기한다',icon:'↩️',req:null,
       reward:{},
       desc:'무조건. 빈손.'},
    ]},

  thorny_brush:{
    name:'가시덤불',
    flavor:'빽빽한 가시덤불이 길을 막고 있다. 안쪽에 뭔가 있는 것 같기도 하다.',
    choices:[
      {label:'잘라서 헤쳐나간다',icon:'🔪',req:null,subReq:'날카로움',
       reward:{cards:[{id:'wood',n:1},{id:'herb',n:1}]},failPen:{hp:-5},
       desc:'#날카로움 판정. 성공:목재×1+약초×1 / 실패:HP-5'},
      {label:'방어구로 돌파',icon:'🛡️',req:null,subReq:'방어구',
       reward:{card:'wood',n:1},failPen:{hp:-3},
       desc:'#방어구 판정. 성공:목재×1 / 실패:HP-3'},
      {label:'우회한다',icon:'🚶',req:null,
       reward:{},
       desc:'무조건. 빈손.'},
    ]},

  cliff_anchor:{
    name:'가파른 절벽',
    flavor:'절벽 아래로 뭔가가 보인다. 내려가려면 단단히 고정해야 할 것 같다.',
    choices:[
      {label:'밧줄로 안전하게 하강',icon:'🪢',req:null,subReq:'줄',
       reward:{card:'food',n:1,san:8},failPen:{},
       desc:'#줄 판정. 성공:식량×1+정신력+8 / 실패:빈손'},
      {label:'무거운 것으로 눌러 확보',icon:'⚒️',req:null,subReq:'무거움',
       reward:{card:'food',n:1},failPen:{hp:-5},
       desc:'#무거움 판정. 성공:식량×1 / 실패:HP-5'},
      {label:'포기한다',icon:'↩️',req:null,
       reward:{},
       desc:'무조건. 빈손.'},
    ]},

  stormy_shore:{
    name:'폭풍우 해안',
    flavor:'갑작스러운 폭풍이 몰아친다. 대처하지 못하면 큰 피해를 입을 것 같다.',
    choices:[
      {label:'밧줄로 몸을 고정',icon:'🪢',req:null,subReq:'줄',
       reward:{san:8},failPen:{hp:-15},
       desc:'#줄 판정. 성공:정신력+8 / 실패:HP-15'},
      {label:'방어구로 버텨낸다',icon:'🛡️',req:null,subReq:'방어구',
       reward:{},failPen:{hp:-8},
       desc:'#방어구 판정. 성공:무피해 / 실패:HP-8'},
      {label:'대피소를 찾는다',icon:'🏠',req:'tool',
       reward:{},failPen:{hp:-15,san:-10},
       desc:'도구판정. 성공:무피해 / 실패:HP-15+정신력-10'},
    ]},

  ancient_altar:{
    name:'오래된 제단',
    flavor:'이끼 낀 돌 제단. 표면에 새겨진 문양이 희미하게 빛나는 것 같다.',
    choices:[
      {label:'뾰족한 것으로 문양을 새긴다',icon:'✒️',req:null,subReq:'뾰족함',
       reward:{san:15,ap:1},failPen:{},
       desc:'#뾰족함 판정. 성공:정신력+15+AP환급 / 실패:빈손'},
      {label:'물건을 바친다',icon:'📦',req:'resource',
       reward:{san:8},failPen:{},
       desc:'자원판정. 성공:정신력+8 / 실패:빈손'},
      {label:'무시하고 지나친다',icon:'🚶',req:null,
       reward:{},
       desc:'무조건. 빈손.'},
    ]},

  abandoned_cook:{
    name:'버려진 조리터',
    flavor:'누군가 조리했던 흔적이 남아있다. 재료를 잘 다룰 줄 안다면 뭔가 만들 수 있을 것 같다.',
    choices:[
      {label:'식재료 지식으로 조리',icon:'🍖',req:null,subReq:'고기',
       reward:{hp:20,san:5},failPen:{},
       desc:'#고기 판정. 성공:HP+20+정신력+5 / 실패:빈손'},
      {label:'그냥 먹을 수 있는 것만',icon:'🍽️',req:'resource',
       reward:{hp:10},failPen:{hp:-5},
       desc:'자원판정. 성공:HP+10 / 실패:HP-5'},
      {label:'통과한다',icon:'↩️',req:null,
       reward:{},
       desc:'무조건. 빈손.'},
    ]},

  wild_plant_id:{
    name:'야생 식물 군락',
    flavor:'형형색색의 야생 식물들이 자라고 있다. 먹을 수 있는 건지 독이 있는 건지 모르겠다.',
    choices:[
      {label:'열매 지식으로 감별',icon:'🫐',req:null,subReq:'열매',
       reward:{cards:[{id:'berry',n:2},{id:'herb',n:1}]},failPen:{},
       desc:'#열매 판정. 성공:작은열매×2+약초×1 / 실패:빈손'},
      {label:'무작정 먹어본다',icon:'🍽️',req:'resource',
       reward:{hp:8,san:5},failPen:{hp:-12,san:-8},
       desc:'자원판정. 성공:HP+8+정신력+5 / 실패:HP-12+정신력-8'},
      {label:'통과한다',icon:'↩️',req:null,
       reward:{},
       desc:'무조건. 빈손.'},
    ]},

  wounded_prey:{
    name:'부상당한 먹잇감',
    flavor:'다리를 절고 있는 동물이 눈에 띈다. 처리만 잘 할 수 있다면 풍족한 식사가 될 것 같다.',
    choices:[
      {label:'능숙하게 처리한다',icon:'🦴',req:null,subReq:'고기',
       reward:{card:'food',n:2,hp:5},failPen:{},
       desc:'#고기 판정. 성공:식량×2+HP+5 / 실패:빈손'},
      {label:'사냥 도구로 마무리',icon:'🔧',req:'tool',
       reward:{card:'food',n:1},failPen:{hp:-8},
       desc:'도구판정. 성공:식량×1 / 실패:HP-8'},
      {label:'그냥 보내준다',icon:'🐾',req:null,
       reward:{san:5},
       desc:'무조건. 정신력+5.'},
    ]},

  river_berries:{
    name:'강가 열매 군락',
    flavor:'강변에 열매가 잔뜩 열려있다. 어떤 건 먹어도 되고 어떤 건 독이 있을 것 같다.',
    choices:[
      {label:'열매 지식으로 수확',icon:'🫐',req:null,subReq:'열매',
       reward:{card:'berry',n:3},failPen:{},
       desc:'#열매 판정. 성공:작은열매×3 / 실패:빈손'},
      {label:'조심스럽게 일부만',icon:'🤲',req:'resource',
       reward:{card:'berry',n:1},failPen:{},
       desc:'자원판정. 성공:작은열매×1 / 실패:빈손'},
      {label:'통과한다',icon:'↩️',req:null,
       reward:{},
       desc:'무조건. 빈손.'},
    ]},

  // ── 균사의 늪 (섬4) 전용 이벤트 ──
  myc_gather:{
    name:'균사 밭',
    flavor:'습지 깊숙이 균사가 가득 퍼져있다. 위험하지만 유용한 재료가 될 것 같다.',
    choices:[
      {label:'조심히 수확한다',icon:'🍄',req:'tool',
       reward:{card:'mycelium',n:2},failPen:{hp:-8},
       desc:'도구판정. 성공:균사×2 / 실패:HP-8'},
      {label:'맨손으로 캔다',icon:'🤲',req:null,
       reward:{card:'spore',n:1},
       desc:'무조건. 포자×1 획득.'},
      {label:'통과한다',icon:'↩️',req:null,
       reward:{},
       desc:'무조건. 빈손.'},
    ]},
  myc_purify:{
    name:'정화 의식',
    flavor:'늪 한가운데 수정처럼 맑은 구역이 있다. 균사가 정화될 것 같다.',
    choices:[
      {label:'정화 의식을 치른다',icon:'✨',req:'resource',
       reward:{removeCard:'rotten_food',san:8},failPen:{san:-5},
       desc:'자원판정. 성공:덱의 썩은음식 1장 제거+정신력+8 / 실패:정신력-5'},
      {label:'그냥 지나친다',icon:'↩️',req:null,
       reward:{},
       desc:'무조건. 빈손.'},
    ]},
  myc_hazard:{
    name:'독성 포자 구름',
    flavor:'노란 포자 구름이 피어오른다. 피해야 한다.',
    choices:[
      {label:'방어구로 막는다',icon:'🛡️',req:null,subReq:'방어구',
       reward:{san:5},failPen:{san:-4},
       desc:'#방어구 판정. 성공:정신력+5 / 실패:정신력-4'},
      {label:'빠르게 통과한다',icon:'💨',req:null,
       reward:{},failPen:{hp:-6,san:-3},
       fixed:true,
       desc:'무조건. HP-6, 정신력-3.'},
    ]},
  myc_fungal:{
    name:'균류 군락',
    flavor:'거대한 버섯들이 가득하다. 먹을 수 있을까?',
    choices:[
      {label:'열매 지식으로 감별',icon:'🫐',req:null,subReq:'열매',
       reward:{cards:[{id:'food',n:1},{id:'mycelium',n:1}]},failPen:{},
       desc:'#열매 판정. 성공:식량×1+균사×1 / 실패:빈손'},
      {label:'조금만 뜯어먹는다',icon:'🍽️',req:'resource',
       reward:{hp:5},failPen:{hp:-10,san:-5},
       desc:'자원판정. 성공:HP+5 / 실패:HP-10+정신력-5'},
      {label:'통과한다',icon:'↩️',req:null,
       reward:{},
       desc:'무조건. 빈손.'},
    ]},
  myc_tree:{
    name:'균사 나무',
    flavor:'뿌리가 맵 전체를 감싸는 듯한 거대한 나무. 균사가 가득 맺혀있다.',
    choices:[
      {label:'균사를 채집한다',icon:'🍄',req:'tool',
       reward:{card:'mycelium',n:3,san:5},failPen:{hp:-6},
       desc:'도구판정. 성공:균사×3+정신력+5 / 실패:HP-6'},
      {label:'나무에 귀를 기울인다',icon:'👂',req:null,
       reward:{san:10},
       desc:'무조건. 신비한 감각. 정신력+10.'},
    ]},
  myc_shrine_ev0:{
    name:'포자 제단의 속삭임',
    flavor:'제단 앞에서 균사 덩어리가 형상을 이루더니 속삭인다. 무언가를 느낄 수 있다.',
    choices:[
      {label:'균사를 바쳐 탐색',icon:'🍄',req:'resource',
       reward:{san:10},failPen:{san:-5},
       desc:'자원판정. 성공:정신력+10 + 보스 정보 획득 / 실패:정신력-5'},
      {label:'그냥 살핀다',icon:'👁️',req:null,reward:{san:5},
       desc:'무조건. 정신력+5. 보스 정보도 간략하게 얻는다.'},
    ]},
  myc_shrine_ev1:{
    name:'균사의 첫 번째 문',
    flavor:'제단 안쪽 통로에 균사가 빼곡하게 얽혀 있다. 길이 보이지 않는다. 지도를 꺼내 확인한다.',
    choices:[
      {label:'균사 사이를 헤치며',icon:'💪',req:'tool',
       reward:{san:8},failPen:{hp:-10},
       desc:'도구판정. 성공:정신력+8 + ATK+2 버프 / 실패:HP-10'},
      {label:'포자 마시며 강행',icon:'💨',req:null,
       reward:{san:5},failPen:{hp:-5,san:-5},
       desc:'무조건 통과. HP-5 정신력-5.'},
    ]},
  myc_shrine_ev2:{
    name:'균사의 두 번째 방',
    flavor:'방 한가운데 거대한 균사 덩어리가 맥박처럼 뛰고 있다. 다가가면 뭔가가 달라질 것 같다.',
    choices:[
      {label:'균사를 흡수한다',icon:'🧫',req:null,subReq:'고기',
       reward:{hp:15,san:5},failPen:{san:-8},
       desc:'#고기 판정. 성공:HP+15 정신력+5 / 실패:정신력-8'},
      {label:'조심스럽게 채취',icon:'🍄',req:'tool',
       reward:{card:'mycelium',n:3},failPen:{hp:-8},
       desc:'도구판정. 성공:균사×3 / 실패:HP-8'},
    ]},
  myc_boss_rot_intro:{
    name:'부패의 여왕 — 경고',
    flavor:'깊은 곳에서 달콤한 썩음 냄새가 올라온다.\n균사가 속삭인다: "먹을 것을 가져왔구나. 내 것이 될 것들을."\n\n⚠️ 보스 특성: 매 라운드 네 덱의 식량 1장이 썩은 음식으로 변한다.\n썩은 음식을 공격존에 배치하면 적이 그것을 먹고 회복한다.\n균사 덩어리를 충분히 준비하고 오는 것이 좋다.',
    choices:[
      {label:'균사 덩어리로 배를 채운다',icon:'🧫',req:null,subReq:'고기',
       reward:{hp:20,hun:20},failPen:{hun:-5},
       desc:'#고기 판정. 성공:HP+20 허기+20 / 실패:허기-5'},
      {label:'정신을 집중한다',icon:'🧘',req:null,reward:{san:12},
       desc:'무조건. 정신력+12.'},
    ]},
  myc_boss_spore_intro:{
    name:'포자 폭군 — 경고',
    flavor:'깊은 곳에서 짙은 보라색 포자 구름이 밀려온다.\n균사가 속삭인다: "독은 이미 네 폐 속에 있다."\n\n⚠️ 보스 특성: 매 라운드 독이 1스택 누적된다(매라운드 HP-3씩 증가).\n체력도 매 라운드 재생한다. 빠르고 강하게 치는 것이 핵심.\n약초와 해독 아이템을 준비하면 유리하다.',
    choices:[
      {label:'약초로 해독 준비',icon:'🌿',req:'resource',
       reward:{hp:12,san:5},failPen:{san:-5},
       desc:'자원판정. 성공:HP+12 정신력+5 / 실패:정신력-5'},
      {label:'정신을 집중한다',icon:'🧘',req:null,reward:{san:12},
       desc:'무조건. 정신력+12.'},
    ]},
  myc_spore_exchange:{
    name:'포자 제단 — 제물 교환',
    flavor:'균사가 천천히 움직이며 무언가를 원하는 것 같다. 포자를 바치면 섬의 자원을 내어줄 것 같다.',
    choices:[
      {label:'포자 → 목재',icon:'🪵',req:null,devourCard:'spore',
       reward:{card:'wood',n:2},
       desc:'포자 1개 소멸 → 목재×2'},
      {label:'포자 → 고철',icon:'⚙️',req:null,devourCard:'spore',
       reward:{card:'metal',n:2},
       desc:'포자 1개 소멸 → 고철×2'},
      {label:'포자 → 돌',icon:'🪨',req:null,devourCard:'spore',
       reward:{card:'stone',n:2},
       desc:'포자 1개 소멸 → 돌×2'},
      {label:'그냥 간다',icon:'↩️',req:null,reward:{},
       desc:'무조건. 빈손.'},
    ]},
};

const RECIPES=[
  {id:'r_knife',   cat:'생존',name:'칼',       icon:'🔪',result:'knife',          rn:1,ap:1,cost:[{id:'wood',n:1},{id:'metal',n:2}],  desc:'패시브:식량회복+8. 전투ATK4.'},
  {id:'r_torch',   cat:'수집',name:'횃불',     icon:'🕯️',result:'torch',          rn:1,ap:1,cost:[{id:'wood',n:2}],                   desc:'패시브:탐색추가보상. 폐허수집장비.'},
  {id:'r_rope',    cat:'생존',name:'밧줄',     icon:'🪢',result:'rope',           rn:1,ap:1,cost:[{id:'wood',n:1},{id:'food',n:1}],   desc:'패시브:드로우+1. 방어DEF3.'},
  {id:'r_axe',     cat:'수집',name:'도끼',     icon:'🪓',result:'axe',            rn:1,ap:1,cost:[{id:'wood',n:2},{id:'metal',n:1}],  desc:'숲 나무베기. 전투ATK3.'},
  {id:'r_gknife',  cat:'수집',name:'채집칼',   icon:'🗡️',result:'gathering_knife',rn:1,ap:1,cost:[{id:'metal',n:2}],                  desc:'숲 약초채집. 전투ATK2.'},
  {id:'r_frod',    cat:'수집',name:'낚싯대',   icon:'🎣',result:'fishing_rod',    rn:1,ap:1,cost:[{id:'wood',n:2},{id:'metal',n:1}],  desc:'해변·해안 낚시. 방어DEF2.'},
  {id:'r_canteen', cat:'수집',name:'물통',     icon:'🫙',result:'canteen',        rn:1,ap:1,cost:[{id:'metal',n:2}],                  desc:'해안 물 채집. 방어DEF2.'},
  {id:'r_pick',    cat:'수집',name:'곡괭이',   icon:'⛏️',result:'pickaxe',       rn:1,ap:1,cost:[{id:'wood',n:1},{id:'metal',n:2},{id:'stone',n:1}],  desc:'동굴 채굴·채석. 전투ATK3. 목재+고철×2+돌.'},
  {id:'r_spear',   cat:'전투',name:'창',       icon:'🗡️',result:'spear',         rn:1,ap:2,cost:[{id:'wood',n:2},{id:'metal',n:2},{id:'stone',n:1}],  desc:'관통특수. ATK8+4관통. 목재×2+고철×2+돌.'},
  {id:'r_larmor',  cat:'전투',name:'가죽갑옷', icon:'🧥',result:'leather_armor',  rn:1,ap:1,cost:[{id:'hide',n:2}],                  desc:'패시브:전투피해-2. DEF4. 가죽×2.'},
  {id:'r_pknife',  cat:'전투',name:'독칼',     icon:'☠️',result:'poison_knife',   rn:1,ap:1,cost:[{id:'hide',n:1},{id:'venom',n:1}],  desc:'독:매라운드+3피해. ATK6. 가죽+독낭.'},
  {id:'r_fcloak',  cat:'전투',name:'깃털망토', icon:'🧣',result:'feather_cloak',  rn:1,ap:1,cost:[{id:'feather',n:2}],               desc:'패시브:도망비용HP-2. DEF2. 깃털×2.'},
  {id:'r_compass', cat:'탈출',name:'유물나침반',icon:'🧭',result:'compass',       rn:1,ap:1,cost:[{id:'shard',n:2}],                  desc:'즉시 탈출도+20%. 고대파편×2.'},
  {id:'r_trap',       cat:'전투',name:'함정',         icon:'🪤',result:'trap',          rn:1,ap:1,cost:[{id:'stone',n:1},{id:'wood',n:1},{id:'metal',n:1}],     desc:'기절: 배정 시 적 다음라운드 피해 0. ATK5. 돌+목재+고철.'},
  {id:'r_stone_hammer',cat:'전투',name:'돌 망치',      icon:'⚒️',result:'stone_hammer',  rn:1,ap:1,cost:[{id:'stone',n:2},{id:'wood',n:1}],                      desc:'ATK6 DEF2. 돌×2 목재×1.'},
  {id:'r_war_club',   cat:'전투',name:'전쟁 몽둥이',  icon:'🏏',result:'war_club',      rn:1,ap:1,cost:[{id:'stone',n:2},{id:'metal',n:1}],                     desc:'crush: DEF 절반 무시. ATK7. 돌×2 고철×1.'},
  {id:'r_bone_blade', cat:'전투',name:'뼈칼',         icon:'🦴',result:'bone_blade',    rn:1,ap:1,cost:[{id:'hide',n:1},{id:'stone',n:1}],                      desc:'bleed: 매라운드 누적피해. ATK5. 가죽×1 돌×1.'},
  {id:'r_w_shield',   cat:'전투',name:'나무 방패',    icon:'🛡️',result:'wooden_shield', rn:1,ap:1,cost:[{id:'stone',n:1},{id:'wood',n:2}],                      desc:'완전방어+5. DEF6. 돌×1 목재×2.'},
  {id:'r_s_vest',     cat:'전투',name:'돌 조끼',      icon:'🦺',result:'stone_vest',    rn:1,ap:1,cost:[{id:'stone',n:2},{id:'hide',n:1}],                      desc:'패시브:피해-3. DEF4. 돌×2 가죽×1.'},
  {id:'r_curse_blade',cat:'전투',name:'저주의 칼',    icon:'🌑',result:'curse_blade',   rn:1,ap:1,cost:[{id:'venom',n:1},{id:'shard',n:1}],                     desc:'weaken: 적 ATK영구-4. ATK4. 독낭+파편.'},
  {id:'r_shatter_blow',cat:'전투',name:'파쇄 해머',   icon:'🔨',result:'shattering_blow',rn:1,ap:1,cost:[{id:'stone',n:2},{id:'metal',n:1}],                   desc:'shatter: 적 DEF영구-6. ATK3. 돌×2 고철×1.'},
  {id:'r_temple_map', cat:'탈출',name:'사원지도',     icon:'🏛️',result:'temple_map',    rn:1,ap:1,cost:[{id:'temple_map_piece',n:3}],                           desc:'사원의 위치를 밝힌다. 조각×3.'},
  {id:'r_myc_chunk', cat:'균사', name:'균사 덩어리', icon:'🧫', result:'myc_chunk', rn:1, ap:1,
   cost:[{id:'mycelium',n:1},{id:'rotten_food',n:1}],
   desc:'균사로 썩은음식 정화. 균사×1+썩은음식×1 → 균사덩어리(허기+10, 썩지않음).'},
  {id:'r_myc_map', cat:'균사', name:'균사지도', icon:'🗺️', result:'myc_map', rn:1, ap:1,
   cost:[{id:'myc_map_piece',n:3}],
   desc:'균사지도 조각×3 → 포자 제단 페이즈 도전 해금 지도.'},
  {id:'r_lure',    cat:'수집',name:'유인 미끼',  icon:'🪤',result:'lure',          rn:1,ap:1,cost:[{id:'food',n:1},{id:'wood',n:1}],   desc:'야생 동물 유인 → 회피불가 강제 전투. 내구도1. 식량×1 목재×1.'},
  {id:'r_flare_kit', cat:'탈출', name:'신호탄 키트', icon:'🧨', result:'flare_kit', rn:1, ap:1,
   cost:[{id:'metal',n:1},{id:'wood',n:1}],
   desc:'전망대에서 구조신호를 탐색하는 도구. 금속×1 목재×1.'},
  // 뗏목 — 뽑기 시스템 (대성공1/성공3/실패1)
  {id:'r_raft',    cat:'탈출',name:'뗏목 부품',icon:'🛶',result:null,             rn:0,ap:2,cost:[{id:'wood',n:3},{id:'metal',n:1}],
   desc:'대성공(1/5): +30%  성공(3/5): +15%  실패(1/5): -10%', raftLottery:true},
];

// O(1) 카드 조회 맵 — CARDS.find() 대신 CARD_MAP[id] 사용
const CARD_MAP = Object.fromEntries(CARDS.map(c=>[c.id,c]));

// ── 스킬 시스템 상수 ──
const SKILL_THRESHOLDS = {
  move:    63,   // G.tilesMoved
  explore: 18,
  gather:  13,
  camp:     5,
  craft:   18,
  carduse: 36,
  sleep:   22,
  combat:   5,
};
const SKILL_POOL = {
  move:    ['sk_mv_b','sk_mv_s1','sk_mv_s2','sk_mv_s3','sk_mv_g'],
  explore: ['sk_ex_b','sk_ex_s1','sk_ex_s2','sk_ex_s3','sk_ex_g'],
  gather:  ['sk_ga_b','sk_ga_s1','sk_ga_s2','sk_ga_s3','sk_ga_g'],
  camp:    ['sk_cp_b','sk_cp_s1','sk_cp_s2','sk_cp_s3','sk_cp_g'],
  craft:   ['sk_cr_b','sk_cr_s1','sk_cr_s2','sk_cr_s3','sk_cr_g'],
  carduse: ['running','sk_cu_s1','sk_cu_s2','sk_cu_s3','sk_cu_g'],
  sleep:   ['sk_sl_b','sk_sl_s1','sk_sl_s2','sk_sl_s3','sk_sl_g'],
  combat:  ['sk_cb_b','sk_cb_s1','sk_cb_s2','sk_cb_s3','sk_cb_g'],
};
const SKILL_TIER_WEIGHTS = {bronze:4, silver:3, gold:1};

// ─── 섬 정의 ───────────────────────────────────────────
// 향후 섬 추가 시 여기에 객체 추가 (id, name, icon, subtitle, story, mechanic, doomName, startLog)
const ISLANDS = {
  mangrove: {
    id: 'mangrove',
    name: '망각의 맹그로브 섬',
    icon: '🌿',
    subtitle: '기억을 잃은 자의 섬',
    story: '정신을 차렸을 때, 이름조차 떠오르지 않았다.\n\n습한 공기, 뒤엉킨 맹그로브 뿌리들, 조용히 흐르는 검은 물.\n여기가 어딘지, 어떻게 왔는지 — 아무것도 기억나지 않는다.\n\n숲 너머로 바다가 보인다. 섬은 조용하고, 그 조용함이 더 무섭다.\n오래 있을수록 안개가 머릿속을 채워간다.\n\n탈출해야 한다. 기억이 완전히 사라지기 전에.',
    mechanic: '🌀 망각의 안개\nDOOM이 높아질수록 짙어지는 안개가 정신력을 가속 소모시킨다.\nDOOM 80% 이후, 탐색·수면 중 망각 상태이상 카드가 덱에 침투한다.\n망각 카드가 판정에 뽑히면 정신력-3. 오래 머물수록 기억이 무너진다.',
    doomName: '망각의 안개',
    doomIcon: '🌫️',
    startLog: '🌿 망각의 맹그로브 섬에 홀로 깨어났다. 기억이 흐릿하다.',
    mapConfig: {
      baseTiles: ['beach','forest','cave','ruins','shore'],
      specialTiles: [
        {id:'lookout',     count:1,   minDist:5, group:'escape'},
        {id:'oblivion_lake',count:1,  minDist:3},
        {id:'oblivion_swamp',count:2, minDist:3},
        {id:'temple',      count:1,   minDist:5, group:'escape'},
        {id:'thicket',     count:[0,2],minDist:2},
      ],
    },
  },
  mycelium: {
    id: 'mycelium',
    name: '균사의 늪',
    icon: '🍄',
    subtitle: '포자가 기억을 바꾸는 섬',
    story: '눈을 떴을 때, 달콤하고 낯선 냄새가 코를 찔렀다.\n\n온 사방이 습기와 균사로 뒤덮여 있다. 발을 내딛을 때마다 포자가 피어오른다.\n\n식량을 구했는데, 밤새 곰팡이가 폈다.\n믿었던 것이 독이 되는 섬.\n\n빠져나가야 한다. 이 균사가 기억까지 바꾸기 전에.',
    mechanic: '🍄 균사 잠식\n매 취침마다 덱의 식량 카드 25%가 썩은 음식으로 변질된다.\n변질된 음식을 섭취하면 HP-5, 정신력-3.\nDOOM 60% 이후 포자 카드가 덱에 침투한다.',
    doomName: '균사 잠식',
    doomIcon: '🍄',
    startLog: '🍄 균사의 늪에서 눈을 떴다. 습한 공기에서 달콤하고 낯선 냄새가 난다.',
    mapConfig: {
      baseTiles: ['swamp','swamp','swamp','forest','shore','shore','cave','beach'],
      specialTiles: [
        {id:'swamp_watch',  count:1,   minDist:5, group:'escape'},
        {id:'fungal_spot',  count:4,   minDist:2},
        {id:'spore_shrine', count:1,   minDist:5, group:'escape'},
        {id:'mycelium_tree',count:1,   minDist:3},
        {id:'thicket',      count:[0,1],minDist:2},
      ],
    },
  },
};
